conversion_tweaks:
  dlc_songs:
    include: false
  enable: false
  max_video_size: 50
  no_medley: false
  pitch_correction: fast
  still_video: false
core:
  id: 01001C101ED10000
dlc:
  id: AAAAAAAAAAAAAAAA
folders:
  input: C:\Users\anton\Desktop\project
  output: C:\Users\anton\Desktop\project\_Patch
tools:
  ffmpeg_path: C:\Users\anton\git\ultrastar2singIt\ffmpeg\bin\ffmpeg.exe
  rad_path: C:\Program Files (x86)\RADVideo\radvideo64.exe
